[package]
name = "marine-utils"
description = "Fluence Marine utils crate"
version = "0.5.1"
authors = ["Fluence Labs"]
repository = "https://github.com/fluencelabs/marine"
license = "AGPL-3.0-only"
edition = "2021"

[lib]
name = "marine_utils"
path = "src/lib.rs"
